---
- name: PLAY <WEBSITE CONSTRUCTION>
  hosts: web1
  vars:
    author: TrangTo
  become: yes
  tasks:
    - name: TASK <install nginx>
      yum: name=nginx state=latest
    - name: TASK <start nginx>
      service:
        name: nginx
        enabled: yes
        state: started
    - name: TASK <update web page>
      template:
        src: ./index.html.j2
        dest: /usr/share/nginx/html/index.html
        
